# SPDX-License-Identifier: Apache-2.0
# Example values for deploying \xCE\xB1-AGI Insight with Helm.
# These settings enable offline mode and map service ports.
image: ghcr.io/example/alpha-insight:latest
replicaCount: 2
env:
  OPENAI_API_KEY: "sk-REPLACE-ME"
  RUN_MODE: api
  AGI_INSIGHT_OFFLINE: "1"
  AGI_INSIGHT_BUS_PORT: "7000"
  AGI_INSIGHT_LEDGER_PATH: "/data/ledger/audit.db"
service:
  type: NodePort
  port: 8080
  uiPort: 8585
  busPort: 7000
