# Prometheus config for Era-of-Experience demo
# Pulls metrics from Pushgateway and itself

global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL:-15s}

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['prom-push:9091']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
