apiVersion: batch/v1
kind: CronJob
metadata:
  name: spot-gpu-worker
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: worker
              image: evolution-worker:latest
              args: ["--process-queue"]
              resources:
                limits:
                  nvidia.com/gpu: 1
