from typing import Any

class BaseAgent:
    name: str
    bus: Any
    ledger: Any
    llm: Any | None
    oai_ctx: Any | None
    adk: Any | None
    mcp: Any | None
    def __init__(self, name: str, bus: Any, ledger: Any, *, backend: str = ..., island: str = ...) -> None: ...
    async def emit(self, target: str, payload: dict[str, Any]) -> None: ...
    def close(self) -> None: ...
    async def handle(self, env: Any) -> None: ...
    async def run_cycle(self) -> None: ...
