apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alpha-demo
  template:
    metadata:
      labels:
        app: alpha-demo
    spec:
      containers:
        - name: orchestrator
          image: {{ .Values.image }}
          env:
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
            - name: RUN_MODE
              value: {{ .Values.env.RUN_MODE | quote }}
            - name: AGI_INSIGHT_OFFLINE
              value: {{ .Values.env.AGI_INSIGHT_OFFLINE | quote }}
            - name: AGI_INSIGHT_BUS_PORT
              value: {{ .Values.env.AGI_INSIGHT_BUS_PORT | quote }}
            - name: AGI_INSIGHT_LEDGER_PATH
              value: {{ .Values.env.AGI_INSIGHT_LEDGER_PATH | quote }}
          ports:
            - containerPort: 8000
            - containerPort: 8501
            - containerPort: 6006
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          volumeMounts:
            - name: ledger
              mountPath: /app/ledger
      volumes:
        - name: ledger
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: alpha-demo-ledger
          {{- else }}
          emptyDir: {}
          {{- end }}
