// Code generated by protoc-gen-go. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
package utils

import (
    proto "google.golang.org/protobuf/proto"
    structpb "google.golang.org/protobuf/types/known/structpb"
)

type Envelope struct {
    Sender    string              `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
    Recipient string              `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
    Payload   *structpb.Struct    `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
    Ts        float64             `protobuf:"fixed64,4,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *Envelope) Reset()         { *x = Envelope{} }
func (x *Envelope) String() string { return proto.CompactTextString(x) }
func (*Envelope) ProtoMessage()    {}
