version: "3.9"

services:
  orchestrator:
    build:
      context: ../..                 # alpha_factory_v1 root
      dockerfile: ./Dockerfile
    image: alpha_factory_orchestrator:selfheal
    env_file: ./config.env
    command: python /app/demo/agent_selfheal_entrypoint.py
    volumes:
      - ./:/app/demo:ro
  ports:
    - "7863:7863"
  depends_on:
    - ollama
  healthcheck:
    test: ["CMD", "curl", "-sf", "http://localhost:7863/__live"]
    interval: 30s
    timeout: 5s
    retries: 3

  ollama:
    image: ollama/ollama:latest
    tty: true
    environment:
      - OLLAMA_MODELS=mixtral:instruct
    volumes:
      - ollama_models:/root/.ollama

  sandbox:
    build:
      context: ../../..
      dockerfile: ../../sandbox.Dockerfile
    image: selfheal-sandbox:latest
    entrypoint: ["/bin/true"]

volumes:
  ollama_models:
