#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# This script is a conceptual research prototype.
# Build the Insight demo and documentation.
# Existing files under $DOCS_DIR that are not generated by the browser build
# are copied aside before the directory is wiped. After unzipping the new
# bundle, those files are restored so manual assets like images or PDFs survive
# across rebuilds.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

BROWSER_DIR="alpha_factory_v1/demos/alpha_agi_insight_v1/insight_browser_v1"
DOCS_DIR="docs/alpha_agi_insight_v1"

usage() {
    cat <<USAGE
Usage: $0

Build the Insight browser bundle, refresh $DOCS_DIR
and generate the mkdocs site.
USAGE
}

if [[ "${1:-}" =~ ^(-h|--help)$ ]]; then
    usage
    exit 0
fi

# Ensure the correct Node.js version before running npm
if ! node "$BROWSER_DIR/build/version_check.js"; then
    echo "ERROR: Node.js 20+ is required to build the Insight docs." >&2
    exit 1
fi

# Fetch WASM assets then install Node dependencies and build the browser bundle
npm --prefix "$BROWSER_DIR" run fetch-assets
npm --prefix "$BROWSER_DIR" ci
npm --prefix "$BROWSER_DIR" run build:dist

# Refresh docs directory with the new bundle while preserving all
# non-generated files (e.g. images or additional Markdown docs)
OLD_DOCS_TEMP=""
if [[ -d "$DOCS_DIR" ]]; then
    OLD_DOCS_TEMP="$(mktemp -d)"
    cp -a "$DOCS_DIR/." "$OLD_DOCS_TEMP/"
fi
rm -rf "$DOCS_DIR"
mkdir -p "$DOCS_DIR"
unzip -q -o "$BROWSER_DIR/insight_browser.zip" -d "$DOCS_DIR"
if [[ -n "$OLD_DOCS_TEMP" ]]; then
    while IFS= read -r -d '' file; do
        rel="${file#"$OLD_DOCS_TEMP"/}"
        target="$DOCS_DIR/$rel"
        if [[ ! -e "$target" ]]; then
            mkdir -p "$(dirname "$target")"
            cp -a "$file" "$target"
        fi
    done < <(find "$OLD_DOCS_TEMP" -mindepth 1 -print0)
    rm -rf "$OLD_DOCS_TEMP"
fi

# Build the MkDocs site
mkdocs build



